"""Django settings for settings project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-e6of16z0i-xf9$dvtjo)32v0#o32*4$4iszk+)0pn(exw_*lj-",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() not in ("false", "0", "no")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "settings.apps.MongoAdminConfig",
    "settings.apps.MongoAuthConfig",
    "settings.apps.MongoContentTypesConfig",
    "settings.apps.SettingsConfig",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_browser_reload",
    "django_watchfiles",
    "rest_framework",
    "drf_spectacular",
    "django_htmx",
    "apps.chat",
    "apps.upload",
    "apps.rag_ingestion",
    "apps.rag_search",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

# In DEBUG, Django's staticfiles finders serve live from STATICFILES_DIRS so
# CSS/JS edits show immediately. WhiteNoise serves the collected snapshot from
# STATIC_ROOT, which would otherwise shadow those live edits -- so only enable
# it in production.
if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "settings.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "settings.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DEFAULT_AUTO_FIELD = "django_mongodb_backend.fields.ObjectIdAutoField"

DATABASE_ROUTERS = ["django_mongodb_backend.routers.MongoRouter"]

MIGRATION_MODULES = {
    "admin": "mongo_migrations.admin",
    "auth": "mongo_migrations.auth",
    "contenttypes": "mongo_migrations.contenttypes",
}


_mongo_host = os.environ.get("MONGO_HOST", "localhost")
_mongo_port = os.environ.get("MONGO_PORT", "27017")
_mongo_db = os.environ.get("MONGO_DB", "exam_gpt")

DATABASES = {
    "default": {
        "ENGINE": "django_mongodb_backend",
        "HOST": f"mongodb://{_mongo_host}:{_mongo_port}/",
        "NAME": _mongo_db,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "staticfiles"]

STATIC_ROOT = BASE_DIR / "static_collected"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Provas GPT API",
    "DESCRIPTION": "API for fetching UFFS schedule data",
    "VERSION": "1.0.0",
    "SORT_OPERATION_PARAMETERS": False,
    "SCHEMA_PATH_PREFIX": r"/api",
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "SERVERS": [{"url": "/api"}],
}
