# Generated by Django 6.0.4 on 2026-05-24 19:11

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número ordinal da questão na prova.')),
                ('enunciado', models.TextField(help_text='Texto completo da questão, incluindo expressões matemáticas em LaTeX inline ($...$).')),
                ('subquestoes', models.JSONField(default=list)),
                ('resposta', models.TextField(help_text='Resposta completa da questão, incluindo explicações e expressões matemáticas em LaTeX inline ($...$).', null=True)),
                ('pontuacao', models.FloatField(help_text='Pontuação da questão.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.TextField()),
                ('cursos', models.JSONField()),
                ('materia', models.TextField()),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('data_aplicacao', models.DateField()),
                ('numero_avaliacao', models.IntegerField()),
                ('questoes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rag_ingestion.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Chunks',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_embedding', django_mongodb_backend.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768)),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rag_ingestion.questao')),
            ],
        ),
    ]
