# Generated by Django 6.0.4 on 2026-05-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prova",
            name="semestre",
            field=models.CharField(max_length=6),
        ),
        migrations.AddConstraint(
            model_name="chunks",
            constraint=models.UniqueConstraint(
                fields=("id_questao",), name="unique_chunk_per_questao"
            ),
        ),
        migrations.AddConstraint(
            model_name="prova",
            constraint=models.UniqueConstraint(
                fields=("materia", "ano", "semestre", "numero_avaliacao"),
                name="unique_prova",
            ),
        ),
        migrations.AddConstraint(
            model_name="questao",
            constraint=models.UniqueConstraint(
                fields=("numero", "enunciado"), name="unique_questao"
            ),
        ),
    ]
