# Generated by Django 6.0.4 on 2026-06-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ingestion', '0002_alter_prova_semestre_chunks_unique_chunk_per_questao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunks',
            name='question_embedding',
        ),
        migrations.AddField(
            model_name='chunks',
            name='turbo_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
