# Generated by Django 6.0.4 on 2026-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ingestion', '0003_remove_chunks_question_embedding_chunks_turbo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='questoes',
        ),
        migrations.AddField(
            model_name='prova',
            name='questoes',
            field=models.ManyToManyField(related_name='provas', to='rag_ingestion.questao'),
        ),
    ]
