# Generated by Django 6.0.4 on 2026-06-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ingestion', '0004_remove_prova_questoes_prova_questoes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prova',
            name='unique_prova',
        ),
        migrations.AddField(
            model_name='prova',
            name='ano_semestre',
            field=models.CharField(default='2026.1', help_text='Ano e semestre no formato YYYY.S (ex: 2026.1 ou 2026.2).', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prova',
            name='nota_final',
            field=models.FloatField(blank=True, help_text='Nota total recebida pelo aluno nesta prova.', null=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='recuperacao',
            field=models.BooleanField(default=False, help_text='True se esta avaliação é uma recuperação.'),
        ),
        migrations.AddField(
            model_name='questao',
            name='nota_recebida',
            field=models.FloatField(blank=True, help_text='Nota recebida pelo aluno nesta questão.', null=True),
        ),
        migrations.AddConstraint(
            model_name='prova',
            constraint=models.UniqueConstraint(fields=('materia', 'ano_semestre', 'numero_avaliacao'), name='unique_prova'),
        ),
        migrations.RemoveField(
            model_name='prova',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='semestre',
        ),
    ]
