# Generated by Django 6.0.6 on 2026-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ingestion', '0006_remove_questao_unique_questao_questao_ordem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(help_text='Texto completo da questão, incluindo expressões matemáticas em LaTeX inline (\\(...\\)) e blocos em $$...$$.'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=models.TextField(help_text='Resposta completa da questão, incluindo explicações e expressões matemáticas em LaTeX inline (\\(...\\)) e blocos em $$...$$.', null=True),
        ),
    ]
